group: edge
dist: trusty

env:
  global:
    TERM=dumb

install: true
before_install:
  - sudo apt update

  # install docker-compose
  - sudo apt install -y python-pip curl jq libxml2-utils
  - sudo pip install docker-compose httpie
  - sudo usermod -aG docker $(whoami)

script:

  - source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/src/stop_any.bash)
  # kill ports to be used
  - stop_any 5432
  - stop_any 80

  - source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/src/wait_for.bash)
  # run nginx and wait for listening port 80
  - docker run -d -p 80:80 --rm --name nginx nginx:alpine
  - wait_for 80
  - http :80/
  - stop_any 80
